### ISSUE TITLE
Confused about Nested Function

### ISSUE THREAD

**Issue by mayasopiie** [impactbyte-drogon-scholarship/discussion#1]
Hello. I am in the process of understanding nested function. I found a code about that, but I am confused about how the way the codes work. Here is the codes.
![screenshot from 2018-07-23 14-14-43](https://user-images.githubusercontent.com/9446897/43062388-dbd5469e-8e82-11e8-8687-6611c436c48f.png)
 Could you please explain to me how the way code on row 7 and 9 work? Thank you

@mhaidarh 
@michaeltamsil

**Comment by mhaidarhanif** [comment]
**Nested functions and closures**

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions

**Comment by michaeltamsil** [comment]
on line 7, the `outside(3)` giving return result of function of line 2.
so the `fn_inside` variable is 'inside' function. "line 2"
