### ISSUE TITLE
Need a summary for Sequelize ORM 

### ISSUE THREAD

**Issue by mayasopiie** [impactbyte-drogon-scholarship/discussion#19]
Hello. Because our lesson today about ORM is pretty long and complicated, so we need a summary about the step of process to use ORM for being a guide for us learning it by ourselves. Please summarize it in detail, Mas. Thank you for helping!

**Comment by mhaidarhanif** [comment]
It's provided in the README of the `impactbyte-learn/code-express-orm-mariadb`: Code Express ORM MariaDB repo

https://github.com/impactbyte-learn/code-express-orm-mariadb

https://github.com/impactbyte-learn/code-express-orm-mariadb/blob/master/README.md
