### ISSUE TITLE
Need confirmation about API Response 

### ISSUE THREAD

**Issue by ariebrainware** [impactbyte-drogon-scholarship/discussion#21]
For make sure, do i need to send message in API Request Response?, consider @michaeltamsil say, the message is unnecesary.. And @mhaidarh  say message is for confirmation that the proccess successfully executed.

Here's some example in my case
![image](https://user-images.githubusercontent.com/26453961/44101687-32f4d318-a012-11e8-8f21-d5f08bab4bf6.png)

and please, ignore the ```result``` variable, just focus on response message

**Comment by michaeltamsil** [comment]
the error message is necessary 
* if wrong logic business like wrong password, wrong username, wrong email
* if internal system have do wrong (query syntax to database)
to know what is wrong so user know how to fix it

[fake server api](https://fakerestapi.azurewebsites.net/swagger/ui/index#/Users)
```js
if on delete && server success then
show nothing but httpcode (200)
else
show message error(to know what is error) & with httpcode(400)
```

play on their site, the playground was good to know what kind API will response to client . this playground was awesome, simple, fun & understand API more.
i prefer right picture from above.
how about you .. what you prefer of?

**Comment by michaeltamsil** [comment]
it's unnecessary to add field of "status": "success" or "status": "error" .. because httpcode is enough & client app read based on httpcode ...so the app code can decide which to execute based on httpcode

**Comment by ariebrainware** [comment]
Thanks.. maybe i should use the right one

**Comment by michaeltamsil** [comment]
line 10 to 12 it should be
```js
.then(result => {
    res.status(200).send(result)
}
```
this will become commonplace on other modules(user, todo, note, etc)

so the result will be
```json
{
"id": "1",
"name": "yoga"
}
```
the result is exactly like in mongodb record or client send data to API server (no add field/key of "user")..your life will be easier with this ... less write do more

not be
```json
{
"user": {
  "id": "1",
  "name": "yoga"
}
```

**Comment by ariebrainware** [comment]
its contact not todo, btw thanks,
