### ISSUE TITLE
Splice() method didn't work for several elements on my array

### ISSUE THREAD

**Issue by mayasopiie** [impactbyte-drogon-scholarship/discussion#7]
Hello. I've been accomplishing Javascript project 2 on level 5. The instruction for that level is to modify recent array by removing some elements with non-string data types. Here is the array.
```js
const names = [
    "Mr. Fahri",
    null,
    undefined,
    "Mr. Abdul",
    24,
    "Mrs. Josephhine",
    "Mr. Joseph",
    "Mr. Paul",
    32,
    "Mrs. Paula",
    7,
    22,
    "Mr. Hakim"
];
```

I made this function to remove any elements with non-string data types. It worked well when I modified it to check any elements with non-string types without leaving any data. But when I modified the function for removing all of non-string type elements using splice() method, it is leaving undefined and 22. Here is the function.
```js
names.forEach(function (name) {
    const checkDataType = typeof name;
    if (checkDataType !== "string") {
        const index = names.indexOf(name);
        if (index !== -1) {
            names.splice(index, 1);
        }
    }
});
```
Could you please help me to find out the problem? Thank you.
Here is the link for the project. I still show the output in the console window. 
https://mayasopiie.github.io/javascript-project-2/level-5/index.html

@mhaidarh 
@michaeltamsil

**Comment by mhaidarhanif** [comment]
https://github.com/mayasopiie/javascript-project-2/blob/master/level-5/index.js

https://github.com/mayasopiie/javascript-project-2/blob/3f15652f975c9737db228dc0e45d58a2b640e6f8/level-5/index.js#L17-L25

**Comment by mayasopiie** [comment]
Mas, give me sort of your previous revision code here please. Thank you @mhaidarh

**Comment by mhaidarhanif** [comment]
Use `filter` method

```js
array.filter((item) => {
    return typeof(item) === "string"
})
```
